version: "3.2"
services:
  redis:
    image: "redis:7.0-alpine"
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    restart: always
  
  api:
    image: "jhawk7/go-redis-mapper:latest"
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8080"

